/*Crear BIG_TIPOCOMPENSATORIOS*/
/*CREATE TABLE "CONSULTA_PBI"."BIG_TIPO_COMPENSATORIO" 
   (	
	"ID_TIPO_COMPENSATORIO" NUMBER(*,0) NOT NULL ENABLE, 
	"TIP_COM_NOMBRE" VARCHAR2(200 BYTE), 
	"TIP_COM_DESCRIPCION" VARCHAR2(200 BYTE), 
  	USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  	STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  	PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  	BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  	TABLESPACE "SIAS_DATA"  ENABLE, 
	 CONSTRAINT "BIG_FUNCIONARIOS_BIG_ROLES_FK" FOREIGN KEY ("ID_ROL")
	  REFERENCES "CONSULTA_PBI"."BIG_ROLES" ("ID_ROL") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SIAS_DATA" ;*/

CREATE TABLE "CONSULTA_PBI"."BIG_TIPO_COMPENSATORIO"
(
   "ID_TIPO_COMPENSATORIO" NUMBER(*,0) NOT NULL ENABLE,
   "TIP_COM_NOMBRE" VARCHAR2(200 BYTE) NOT NULL,
   "TIP_COM_DESCRIPCION" VARCHAR2(200 BYTE) NOT NULL
)
SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "SIAS_DATA";


CREATE OR REPLACE TRIGGER "CONSULTA_PBI"."BIG_TIPO_COMPENSATORIO_TRIGGER"
BEFORE INSERT ON big_tipo_compensatorio
FOR EACH ROW
WHEN (new.id_tipo_compensatorio IS NULL) BEGIN
    :new.id_tipo_compensatorio := BIG_TIPO_COMPENSATORIO_SEQ.nextval;
END;

/
ALTER TRIGGER "CONSULTA_PBI"."BIG_TIPO_COMPENSATORIO_TRIGGER" ENABLE;
/*------------------------------------------------------------------*/
/*Crear BIG_COMPENSATORIOS*/
CREATE TABLE "CONSULTA_PBI"."BIG_COMPENSATORIOS" 
   (	"ID_COMPENSATORIO" NUMBER(*,0) NOT NULL ENABLE, 
	"ID_FUNCIONARIO" NUMBER(*,0) NOT NULL ENABLE, 
	"COM_FECHA_INICIO" TIMESTAMP (6), 
	"COM_FECHA_FIN" TIMESTAMP (6), 
	"COM_ACTIVIDAD_DESARROLLAR" VARCHAR2(200 BYTE), /***/
	"COM_DESCRIPCION_ACTIVIDAD" VARCHAR2(200 BYTE), 
	"COM_ESTADO" VARCHAR2(200 BYTE) DEFAULT '1', 
	"COM_USUARIO_FINAL" VARCHAR2(200 BYTE), 
	"COM_EVIDENCIAS" VARCHAR2(200 BYTE), 
	CONSTRAINT "BIG_COMPENSATORIO_PK" PRIMARY KEY ("ID_COMPENSATORIO")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "SIAS_DATA"  ENABLE, 
	CONSTRAINT "BIG_COM_BIG_FUN_FK" FOREIGN KEY ("ID_FUNCIONARIO")
	REFERENCES "CONSULTA_PBI"."BIG_FUNCIONARIOS" ("ID_FUNCIONARIO") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SIAS_DATA" ;

  CREATE OR REPLACE TRIGGER "CONSULTA_PBI"."BIG_COMPENSATORIO_ID_COMPENSAT" BEFORE
    INSERT ON "BIG_COMPENSATORIOS"
    FOR EACH ROW
     WHEN ( new.id_compensatorio IS NULL ) BEGIN
    :new.id_compensatorio := big_compensatorio_id_compensat.nextval;
END;
--
/
ALTER TRIGGER "CONSULTA_PBI"."BIG_COMPENSATORIO_ID_COMPENSAT" ENABLE;
/*------------------------------------------------------------------*/
/*Crear BIG_FUNCIONARIOS*/
CREATE TABLE "CONSULTA_PBI"."BIG_FUNCIONARIOS" 
   (	"ID_FUNCIONARIO" NUMBER(*,0) NOT NULL ENABLE, 
	"FUN_NOMBRES" VARCHAR2(200 BYTE), 
	"FUN_APELLIDOS" VARCHAR2(200 BYTE), 
	"FUN_IDENTIFICACION" VARCHAR2(200 BYTE), 
	"FUN_CORREO" VARCHAR2(200 BYTE), 
	"FUN_USUARIO" VARCHAR2(200 BYTE), 
	"FUN_PASSWORD" VARCHAR2(200 BYTE), 
	"FUN_TOKEN" VARCHAR2(200 BYTE), 
	"FUN_ESTADO" VARCHAR2(20 BYTE) DEFAULT 1, 
	"ID_ROL" NUMBER(*,0) NOT NULL ENABLE, 
	"FUN_ADMIN" VARCHAR2(20 BYTE) DEFAULT 0, 
	 CONSTRAINT "BIG_FUNCIONARIOS_PK" PRIMARY KEY ("ID_FUNCIONARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SIAS_DATA"  ENABLE, 
	 CONSTRAINT "BIG_FUNCIONARIOS_BIG_ROLES_FK" FOREIGN KEY ("ID_ROL")
	  REFERENCES "CONSULTA_PBI"."BIG_ROLES" ("ID_ROL") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SIAS_DATA" ;

  CREATE OR REPLACE TRIGGER "CONSULTA_PBI"."BIG_FUNCIONARIOS_ID_FUNCIONARI" BEFORE
    INSERT ON big_funcionarios
    FOR EACH ROW
     WHEN ( new.id_funcionario IS NULL ) BEGIN
    :new.id_funcionario := big_funcionarios_id_funcionari.nextval;
END;

/
ALTER TRIGGER "CONSULTA_PBI"."BIG_FUNCIONARIOS_ID_FUNCIONARI" ENABLE;
/*------------------------------------------------------------------*/
/*Crear BIG_MENU*/
CREATE TABLE "CONSULTA_PBI"."BIG_MENU" 
   (	"ID_MENU" NUMBER(*,0) NOT NULL ENABLE, 
	"MEN_TITULO" VARCHAR2(200 BYTE), 
	"MEN_CODIGO" VARCHAR2(200 BYTE), 
	"MEN_ESTADO" VARCHAR2(200 BYTE), 
	"MEN_ICONO" VARCHAR2(200 BYTE), 
	 CONSTRAINT "BIG_MENU_PK" PRIMARY KEY ("ID_MENU")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SIAS_DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SIAS_DATA" ;

  CREATE OR REPLACE TRIGGER "CONSULTA_PBI"."BIG_MENU_ID_MENU_TRG" BEFORE
    INSERT ON big_menu
    FOR EACH ROW
     WHEN ( new.id_menu IS NULL ) BEGIN
    :new.id_menu := big_menu_id_menu_seq.nextval;
END;

/
ALTER TRIGGER "CONSULTA_PBI"."BIG_MENU_ID_MENU_TRG" ENABLE;
/*------------------------------------------------------------------*/
/*Crear BIG_MODULOS*/
CREATE TABLE "CONSULTA_PBI"."BIG_MODULOS" 
   (	"ID_MODULO" NUMBER(*,0) NOT NULL ENABLE, 
	"MOD_TITULO" VARCHAR2(200 BYTE), 
	"MOD_DESCRIPCION" VARCHAR2(200 BYTE), 
	"MOD_ESTADO" VARCHAR2(200 BYTE), 
	"MOD_CODIGO" VARCHAR2(200 BYTE), 
	"MOD_ACCESO" VARCHAR2(200 BYTE), 
	"MOD_LISTAR" VARCHAR2(200 BYTE), 
	"MOD_ICONO" VARCHAR2(200 BYTE), 
	"ID_MENU" NUMBER, 
	 CONSTRAINT "BIG_MODULOS_PK" PRIMARY KEY ("ID_MODULO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SIAS_DATA"  ENABLE, 
	 CONSTRAINT "BIG_MODULOS_FK1" FOREIGN KEY ("ID_MENU")
	  REFERENCES "CONSULTA_PBI"."BIG_MENU" ("ID_MENU") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SIAS_DATA" ;

  CREATE OR REPLACE TRIGGER "CONSULTA_PBI"."BIG_MODULOS_ID_MODULO_TRG" BEFORE
    INSERT ON big_modulos
    FOR EACH ROW
     WHEN ( new.id_modulo IS NULL ) BEGIN
    :new.id_modulo := BIG_MODULOS_ID_MODULO_SEQ.nextval;
END;
/
ALTER TRIGGER "CONSULTA_PBI"."BIG_MODULOS_ID_MODULO_TRG" ENABLE;
/*------------------------------------------------------------------*/
/*Crear BIG_PERMISOS*/
CREATE TABLE "CONSULTA_PBI"."BIG_PERMISOS" 
   (	"ID_PERMISO" NUMBER(*,0) DEFAULT NULL NOT NULL ENABLE, 
	"ID_ROL" NUMBER(*,0) NOT NULL ENABLE, 
	"ID_MODULO" NUMBER(*,0) NOT NULL ENABLE, 
	"PER_R" NUMBER, 
	"PER_W" NUMBER, 
	"PER_U" NUMBER, 
	"PER_D" NUMBER, 
	"PER_F" NUMBER, 
	 CONSTRAINT "BIG_PERMISOS_PK" PRIMARY KEY ("ID_PERMISO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SIAS_DATA"  ENABLE, 
	 CONSTRAINT "BIG_PERMISOS_BIG_MODULOS_FK" FOREIGN KEY ("ID_MODULO")
	  REFERENCES "CONSULTA_PBI"."BIG_MODULOS" ("ID_MODULO") ENABLE, 
	 CONSTRAINT "BIG_PERMISOS_BIG_ROLES_FK" FOREIGN KEY ("ID_ROL")
	  REFERENCES "CONSULTA_PBI"."BIG_ROLES" ("ID_ROL") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SIAS_DATA" ;

  CREATE OR REPLACE TRIGGER "CONSULTA_PBI"."BIG_PERMISOS_ID_PERMISO_TRG" BEFORE
    INSERT ON big_permisos
    FOR EACH ROW
     WHEN ( new.id_permiso IS NULL ) BEGIN
    :new.id_permiso := BIG_PERMISOS_ID_PERMISO_SEQ.nextval;
END;
/
ALTER TRIGGER "CONSULTA_PBI"."BIG_PERMISOS_ID_PERMISO_TRG" ENABLE;
/*------------------------------------------------------------------*/
/*Crear BIG_ROLES*/
CREATE TABLE "BIG_ROLES"."BIG_ROLES" 
   (	"ID_ROL" NUMBER(*,0) NOT NULL ENABLE, 
	"ROL_NOMBRE" VARCHAR2(200 BYTE), 
	"ROL_DESCRIPCION" VARCHAR2(200 BYTE), 
	"ROL_ESTADO" VARCHAR2(200 BYTE) DEFAULT '1', 
	"ROL_CODIGO" VARCHAR2(200 BYTE), 
	 CONSTRAINT "BIG_ROLES_PK" PRIMARY KEY ("ID_ROL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SIAS_DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SIAS_DATA" ;

  CREATE OR REPLACE TRIGGER "CONSULTA_PBI"."BIG_ROLES_ID_ROL_TRG" BEFORE
    INSERT ON big_roles
    FOR EACH ROW
     WHEN ( new.id_rol IS NULL ) BEGIN
    :new.id_rol := big_roles_id_rol_seq.nextval;
END;

/
ALTER TRIGGER "CONSULTA_PBI"."BIG_ROLES_ID_ROL_TRG" ENABLE;
/*------------------------------------------------------------------*/
/*Crear BIG_TOMA*/
CREATE TABLE "CONSULTA_PBI"."BIG_TOMA" 
   (	"ID_TOMA" NUMBER(*,0) NOT NULL ENABLE, 
	"TOM_ESTADO" VARCHAR2(200 BYTE) DEFAULT '1', 
	"TOM_MOTIVO" VARCHAR2(200 BYTE), 
	"TOM_FECHA_SOLI" DATE, 
	"TOM_HORAS_SOLI" VARCHAR2(200 BYTE), 
	"ID_FUNCIONARIO" NUMBER(*,0) NOT NULL ENABLE, 
	 CONSTRAINT "BIG_TOMA_COMPE_PK" PRIMARY KEY ("ID_TOMA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SIAS_DATA"  ENABLE, 
	 CONSTRAINT "BIG_TOMA_BIG_FUNCIONARIOS_FK" FOREIGN KEY ("ID_FUNCIONARIO")
	  REFERENCES "CONSULTA_PBI"."BIG_FUNCIONARIOS" ("ID_FUNCIONARIO") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SIAS_DATA" ;

  CREATE OR REPLACE TRIGGER "CONSULTA_PBI"."BIG_TOMA_ID_TOMA_TRG" BEFORE
    INSERT ON big_toma
    FOR EACH ROW
     WHEN ( new.id_toma IS NULL ) BEGIN
    :new.id_toma := big_toma_id_toma_seq.nextval;
END;
/
ALTER TRIGGER "CONSULTA_PBI"."BIG_TOMA_ID_TOMA_TRG" ENABLE;
/*------------------------------------------------------------------*/
