SELECT
			TOM.ID_FUNCIONARIO,
			TOM.ID_TOMA,
			TOM.TOM_ESTADO,
			TOM.TOM_MOTIVO,
			TOM.TOM_FECHA_SOLI,
			TOM.TOM_HORAS_SOLI
		FROM BIG_TOMA TOM
		WHERE TOM.ID_TOMA = 111;
        
UPDATE BIG_TOMA
			SET TOM_MOTIVO = 'Yyppp8881',
			TOM_FECHA_SOLI = TO_DATE('24/07/2024', 'DD/MM/YYYY'),
			TOM_HORAS_SOLI = 0.5
			WHERE ID_TOMA = 111;
            
UPDATE BIG_TOMA
			SET TOM_MOTIVO = :TOM_MOTIVO,
			TOM_FECHA_SOLI = TO_DATE(:TOM_FECHA_SOLI, 'DD/MM/YYYY'),
			TOM_HORAS_SOLI = :TOM_HORAS_SOLI
			WHERE ID_TOMA = 111;

/*SELECT
    F.FUN_NOMBRES || ' ' ||F.FUN_APELLIDOS NOMBREFUNCIONARIO,
    ROUND(SUM(
        CASE WHEN C.COM_ESTADO IN (2) THEN
            EXTRACT(HOUR FROM (C.COM_FECHA_FIN - C.COM_FECHA_INICIO)) +
            EXTRACT(MINUTE FROM (C.COM_FECHA_FIN - C.COM_FECHA_INICIO)) / 60
        ELSE
            0
        END), 2) -  --AS HORAS_TOTALES
   SUM(T.TOM_HORAS_SOLI) AS HORAS_GASTADAS
FROM BIG_COMPENSATORIOS C
INNER JOIN BIG_FUNCIONARIOS F ON C.ID_FUNCIONARIO = F.ID_FUNCIONARIO
INNER JOIN BIG_TOMA T ON C.ID_FUNCIONARIO = T.ID_FUNCIONARIO
WHERE C.ID_FUNCIONARIO = 26 AND T.TOM_ESTADO =2 AND C.COM_ESTADO = 2 
GROUP BY T.ID_FUNCIONARIO, F.FUN_NOMBRES, F.FUN_APELLIDOS;

SELECT T.ID_FUNCIONARIO,
    
    FROM 
WHERE T.ID_FUNCIONARIO = 26 
GROUP BY ;*/
--& T.TOM_ESTADO)
SELECT
    ROUND(SUM(T.TOM_HORAS_SOLI), 2) AS TOM_HORAS_SOLI,
    ROUND(SUM(EXTRACT(HOUR FROM (C.COM_FECHA_FIN - C.COM_FECHA_INICIO)) +
          EXTRACT(MINUTE FROM (C.COM_FECHA_FIN - C.COM_FECHA_INICIO)) / 60),2) AS COMP_HORAS,
    ROUND(CASE WHEN C.COM_ESTADO = 2 THEN
        SUM(EXTRACT(HOUR FROM (C.COM_FECHA_FIN - C.COM_FECHA_INICIO)) +
          EXTRACT(MINUTE FROM (C.COM_FECHA_FIN - C.COM_FECHA_INICIO)) / 60) - ROUND(SUM(TOM_HORAS_SOLI), 2)
      ELSE
        0
      END, 2) AS DIFERENCIA_HORAS
FROM BIG_COMPENSATORIOS C
INNER JOIN BIG_TOMA T ON C.ID_FUNCIONARIO = T.ID_FUNCIONARIO
WHERE T.ID_FUNCIONARIO = 26 AND T.TOM_ESTADO = 2 AND C.COM_ESTADO = 2
GROUP BY C.ID_FUNCIONARIO, T.TOM_HORAS_SOLI, C.COM_ESTADO, T.TOM_ESTADO, T.TOM_MOTIVO;
    
    //1	2,5	1,5
    //1	2,5	1,5
---------------------------------------------------------------------------------------------------------------------------
DECLARE
    v_horas_disponibles NUMBER;
    v_horas_solicitadas NUMBER;
BEGIN
    -- Obtener el valor de HORAS_DISPONIBLES
    SELECT ROUND(AVG(COMP_HORAS_SUBQUERY), 2) - ROUND(SUM(TOM_HORAS_SOLI_SUBQUERY), 2)
    INTO v_horas_disponibles
    FROM (
        SELECT
            C.ID_FUNCIONARIO,
            T.TOM_HORAS_SOLI,
            C.COM_ESTADO,
            T.TOM_ESTADO,
            T.TOM_MOTIVO,
            T.TOM_FECHA_SOLI,
            T.TOM_HORAS_SOLI AS TOM_HORAS_SOLI_SUBQUERY,
            SUM(EXTRACT(HOUR FROM (C.COM_FECHA_FIN - C.COM_FECHA_INICIO)) +
                EXTRACT(MINUTE FROM (C.COM_FECHA_FIN - C.COM_FECHA_INICIO)) / 60) AS COMP_HORAS_SUBQUERY
        FROM BIG_COMPENSATORIOS C
        INNER JOIN BIG_TOMA T ON C.ID_FUNCIONARIO = T.ID_FUNCIONARIO
        WHERE T.ID_FUNCIONARIO = 26 AND T.TOM_ESTADO = 2 AND C.COM_ESTADO = 2
        GROUP BY C.ID_FUNCIONARIO, T.TOM_HORAS_SOLI, C.COM_ESTADO, T.TOM_ESTADO, T.TOM_MOTIVO, T.TOM_FECHA_SOLI
    );
    -- Obtener el valor de TOM_HORAS_SOLI
    SELECT
        T.TOM_HORAS_SOLI
    INTO v_horas_solicitadas
    FROM BIG_TOMA T
    WHERE T.ID_TOMA = 115;

    -- Condicional para actualizar BIG_TOMA
    IF v_horas_disponibles >= v_horas_solicitadas THEN
        UPDATE BIG_TOMA
        SET TOM_ESTADO = 2
        WHERE ID_TOMA = 115;
    ELSE
        UPDATE BIG_TOMA
        SET TOM_ESTADO = 3
        WHERE ID_TOMA = 115;
    END IF;
END;

   -------------------------------------------------------------------------------------------------------------------
   SELECT
    IF HORAS_DISPONIBLES >= 1 THEN
        UPDATE BIG_TOMA
        SET TOM_ESTADO = 2
        WHERE ID_TOMA = 97;
    ELSE
        UPDATE BIG_TOMA
        SET TOM_ESTADO = 1
        WHERE ID_TOMA = 97;
    END IF;
FROM (
    SELECT
        ROUND(SUM(TOM_HORAS_SOLI_SUBQUERY), 2) AS HORAS_APROBADAS,
        ROUND(AVG(COMP_HORAS_SUBQUERY), 2) AS HORAS_COMPENSATORIOS_APROBADAS,
        AVG(COMP_HORAS_SUBQUERY) - SUM(TOM_HORAS_SOLI_SUBQUERY) AS HORAS_DISPONIBLES
    FROM (
        SELECT
            C.ID_FUNCIONARIO,
            T.TOM_HORAS_SOLI,
            C.COM_ESTADO,
            T.TOM_ESTADO,
            T.TOM_MOTIVO,
            T.TOM_FECHA_SOLI,
            T.TOM_HORAS_SOLI AS TOM_HORAS_SOLI_SUBQUERY,
            SUM(EXTRACT(HOUR FROM (C.COM_FECHA_FIN - C.COM_FECHA_INICIO)) +
                EXTRACT(MINUTE FROM (C.COM_FECHA_FIN - C.COM_FECHA_INICIO)) / 60) AS COMP_HORAS_SUBQUERY
        FROM BIG_COMPENSATORIOS C
        INNER JOIN BIG_TOMA T ON C.ID_FUNCIONARIO = T.ID_FUNCIONARIO
        WHERE T.ID_FUNCIONARIO = 26 AND T.TOM_ESTADO = 2 AND C.COM_ESTADO = 2
        GROUP BY C.ID_FUNCIONARIO, T.TOM_HORAS_SOLI, C.COM_ESTADO, T.TOM_ESTADO, T.TOM_MOTIVO, T.TOM_FECHA_SOLI
    )
)

   -------------------------------------------------------------------------------------------------------------------
            SELECT
                    FUN_NOMBRES || ' ' ||FUN_APELLIDOS AS NOMBREFUNCIONARIO,
					ROUND(SUM(TOM_HORAS_SOLI_SUBQUERY),2) AS HORAS_APROBADAS,
					ROUND(AVG(COMP_HORAS_SUBQUERY),2) AS HORAS_COMPENSATORIOS_APROBADAS,
					AVG(COMP_HORAS_SUBQUERY) - SUM(TOM_HORAS_SOLI_SUBQUERY) AS HORAS_DISPONIBLES
            FROM(
				SELECT
                    F.FUN_NOMBRES,
                    F.FUN_APELLIDOS,
					C.ID_FUNCIONARIO,
					T.TOM_HORAS_SOLI,
					C.COM_ESTADO,
					T.TOM_ESTADO,
					T.TOM_MOTIVO,
					T.TOM_FECHA_SOLI,
					T.TOM_HORAS_SOLI AS TOM_HORAS_SOLI_SUBQUERY,
					SUM(EXTRACT(HOUR FROM (C.COM_FECHA_FIN - C.COM_FECHA_INICIO)) +
						EXTRACT(MINUTE FROM (C.COM_FECHA_FIN - C.COM_FECHA_INICIO)) / 60) AS COMP_HORAS_SUBQUERY
				FROM BIG_COMPENSATORIOS C
				INNER JOIN BIG_TOMA T ON C.ID_FUNCIONARIO = T.ID_FUNCIONARIO
                INNER JOIN BIG_FUNCIONARIOS F ON C.ID_FUNCIONARIO = F.ID_FUNCIONARIO
				WHERE T.ID_FUNCIONARIO = 26 AND T.TOM_ESTADO = 2 AND C.COM_ESTADO = 2
				GROUP BY C.ID_FUNCIONARIO, T.TOM_HORAS_SOLI, C.COM_ESTADO, T.TOM_ESTADO, T.TOM_MOTIVO, 
                T.TOM_FECHA_SOLI, F.FUN_NOMBRES, F.FUN_APELLIDOS) 
                GROUP BY FUN_NOMBRES || ' ' ||FUN_APELLIDOS;
            
SELECT
			FUN.ID_FUNCIONARIO,
			FUN.FUN_NOMBRES,
			FUN.FUN_APELLIDOS,
			FUN.FUN_CORREO,
			FUN.FUN_USUARIO,
			COM.COM_FECHA_INICIO AS COM_FECHA_INICIO,
			COM.COM_FECHA_FIN AS COM_FECHA_FIN,
			TC.TIP_COM_NOMBRE,
			COM.COM_DESCRIPCION_ACTIVIDAD,
			COM.COM_USUARIO_FINAL
		FROM BIG_COMPENSATORIOS COM
		INNER JOIN BIG_FUNCIONARIOS FUN ON FUN.ID_FUNCIONARIO = COM.ID_FUNCIONARIO
		INNER JOIN BIG_TIPO_COMPENSATORIO TC ON COM.ID_TIPO_COMPENSATORIO = TC.ID_TIPO_COMPENSATORIO
		WHERE COM.ID_COMPENSATORIO = 1444;   

SELECT
  C.ID_FUNCIONARIO,
  T.TOM_HORAS_SOLI,
  C.COM_ESTADO,
  T.TOM_ESTADO,
  T.TOM_MOTIVO,
  SUM(T.TOM_HORAS_SOLI) OVER (PARTITION BY C.ID_FUNCIONARIO ORDER BY T.TOM_FECHA_SOLI) AS TOM_HORAS_SOLI_SUBQUERY,
  SUM(EXTRACT(HOUR FROM (C.COM_FECHA_FIN - C.COM_FECHA_INICIO)) +
    EXTRACT(MINUTE FROM (C.COM_FECHA_FIN - C.COM_FECHA_INICIO)) / 60) OVER (PARTITION BY C.ID_FUNCIONARIO ORDER BY T.TOM_FECHA_SOLI) AS COMP_HORAS_SUBQUERY
FROM BIG_COMPENSATORIOS C
INNER JOIN BIG_TOMA T ON C.ID_FUNCIONARIO = T.ID_FUNCIONARIO
WHERE T.ID_FUNCIONARIO = 26 AND T.TOM_ESTADO = 2 AND C.COM_ESTADO = 2;


    
SELECT
  ID_FUNCIONARIO,
  TOM_HORAS_SOLI,
  COMPENSATORIOS,
  TOM_MOTIVO,
  SUM(TOM_HORAS_SOLI - COMPENSATORIOS) AS DIFERENCIA,
  DIFERENCIA_HORAS AS DIFERENCIA_HORAS_REDONDEADA
FROM (
  SELECT
    COUNT(*) AS NUM_REGISTROS,
    TOM_ESTADO,
    TOM_MOTIVO,
    C.ID_FUNCIONARIO,
    ROUND(SUM(T.TOM_HORAS_SOLI), 2) AS TOM_HORAS_SOLI,
    ROUND(SUM(
				CASE WHEN C.COM_ESTADO IN (2) THEN
					EXTRACT(HOUR FROM (C.COM_FECHA_FIN - C.COM_FECHA_INICIO)) +
					EXTRACT(MINUTE FROM (C.COM_FECHA_FIN - C.COM_FECHA_INICIO)) / 60
				ELSE
					0
				END), 2)/COUNT(*) AS COMPENSATORIOS,
    ROUND(SUM(EXTRACT(HOUR FROM (C.COM_FECHA_FIN - C.COM_FECHA_INICIO)) +
      EXTRACT(MINUTE FROM (C.COM_FECHA_FIN - C.COM_FECHA_INICIO)) / 60) - TOM_HORAS_SOLI,2) AS DIFERENCIA_HORAS
  FROM BIG_TOMA T
  INNER JOIN BIG_COMPENSATORIOS C ON C.ID_FUNCIONARIO = T.ID_FUNCIONARIO
  WHERE T.ID_FUNCIONARIO = 26 AND T.TOM_ESTADO = 2 AND C.COM_ESTADO = 2
  GROUP BY C.ID_FUNCIONARIO, T.TOM_ESTADO, TOM_MOTIVO
);

SELECT 
  /*F.FUN_NOMBRES AS FUN_NOMBRES,
  F.FUN_APELLIDOS AS FUN_APELLIDOS,
  F.FUN_CORREO AS FUN_CORREO,
  T.TOM_ESTADO AS TOM_ESTADO,
  C.COM_ESTADO AS COM_ESTADO,
  TO_CHAR(T.TOM_FECHA_SOLI, 'DD/MM/YYYY') AS TOM_FECHA_SOLI,
  T.TOM_MOTIVO,
  T.TOM_HORAS_SOLI AS TOM_HORAS_SOLI,*/
  F.FUN_NOMBRES || ' ' ||F.FUN_APELLIDOS NOMBREFUNCIONARIO,
  ROUND(SUM(TOM_HORAS_SOLI)) AS HORAS_SOLI,

  --ROUND(SUM(TOM_HORAS_SOLI), 2) AS TOTAL_TOM_HORAS_SOLI,
    ROUND(SUM(
  CASE WHEN (BITAND(COM_ESTADO, T.TOM_ESTADO)) = 2 THEN
    EXTRACT(HOUR FROM (C.COM_FECHA_FIN - C.COM_FECHA_INICIO)) +
      EXTRACT(MINUTE FROM (C.COM_FECHA_FIN - C.COM_FECHA_INICIO)) / 60 
  ELSE
    0
  END), 2) - ROUND(
    CASE WHEN (BITAND(COM_ESTADO, T.TOM_ESTADO)) = 2 THEN
        SUM(TOM_HORAS_SOLI)
    ELSE
    0
  END, 2) AS DIFERENCIA_HORAS

FROM BIG_COMPENSATORIOS C
INNER JOIN BIG_FUNCIONARIOS F ON C.ID_FUNCIONARIO = F.ID_FUNCIONARIO
INNER JOIN BIG_TOMA T ON C.ID_FUNCIONARIO = T.ID_FUNCIONARIO
WHERE C.ID_FUNCIONARIO = 26 AND C.COM_ESTADO = 2 AND T.TOM_ESTADO = 2 
GROUP BY C.ID_FUNCIONARIO, F.FUN_NOMBRES, F.FUN_APELLIDOS,
     T.TOM_HORAS_SOLI, T.TOM_ESTADO, C.COM_ESTADO;
--, F.FUN_CORREO, T.TOM_FECHA_SOLI, T.TOM_MOTIVO


/*FROM BIG_COMPENSATORIOS I
INNER JOIN BIG_FUNCIONARIOS F ON I.ID_FUNCIONARIO = F.ID_FUNCIONARIO
INNER JOIN BIG_TOMA T ON I.ID_FUNCIONARIO = T.ID_FUNCIONARIO
WHERE T.ID_TOMA = $this->intIdToma
GROUP BY I.ID_FUNCIONARIO, F.FUN_NOMBRES, F.FUN_APELLIDOS,
F.FUN_CORREO, T.TOM_MOTIVO, T.TOM_FECHA_SOLI, T.TOM_HORAS_SOLI, T.TOM_ESTADO;*/

INSERT INTO BIG_COMPENSATORIOS
			(
				ID_FUNCIONARIO,
				COM_FECHA_INICIO,
				COM_FECHA_FIN,
				ID_TIPO_COMPENSATORIO,
				COM_DESCRIPCION_ACTIVIDAD,
				COM_USUARIO_FINAL,
				COM_EVIDENCIAS,
				COM_ESTADO
			) 
			VALUES
			(
				26,
				TO_TIMESTAMP('04/07/2024 04:00 PM', 'YYYY/MM/DD HH24:MI:SS'),
				TO_TIMESTAMP('04/07/2024 06:00 PM', 'YYYY/MM/DD HH24:MI:SS'),
				20,
				'Prurba',
				'Pruebaa',
				'untitled-2024-06-14-1032.png_668716ee2799a',
				'1'
			);

