/*SELECT
    F.FUN_NOMBRES || ' ' ||F.FUN_APELLIDOS NOMBREFUNCIONARIO,
    ROUND(SUM(
        CASE WHEN C.COM_ESTADO IN (2) THEN
            EXTRACT(HOUR FROM (C.COM_FECHA_FIN - C.COM_FECHA_INICIO)) +
            EXTRACT(MINUTE FROM (C.COM_FECHA_FIN - C.COM_FECHA_INICIO)) / 60
        ELSE
            0
        END), 2) -  --AS HORAS_TOTALES
   SUM(T.TOM_HORAS_SOLI) AS HORAS_GASTADAS
FROM BIG_COMPENSATORIOS C
INNER JOIN BIG_FUNCIONARIOS F ON C.ID_FUNCIONARIO = F.ID_FUNCIONARIO
INNER JOIN BIG_TOMA T ON C.ID_FUNCIONARIO = T.ID_FUNCIONARIO
WHERE C.ID_FUNCIONARIO = 26 AND T.TOM_ESTADO =2 AND C.COM_ESTADO = 2 
GROUP BY T.ID_FUNCIONARIO, F.FUN_NOMBRES, F.FUN_APELLIDOS;

SELECT T.ID_FUNCIONARIO,
    
    FROM 
WHERE T.ID_FUNCIONARIO = 26 
GROUP BY ;*/
--& T.TOM_ESTADO)
SELECT
    ROUND(SUM(T.TOM_HORAS_SOLI), 2) AS TOM_HORAS_SOLI,
    ROUND(SUM(EXTRACT(HOUR FROM (C.COM_FECHA_FIN - C.COM_FECHA_INICIO)) +
          EXTRACT(MINUTE FROM (C.COM_FECHA_FIN - C.COM_FECHA_INICIO)) / 60),2) AS COMP_HORAS,
    ROUND(CASE WHEN C.COM_ESTADO = 2 THEN
        SUM(EXTRACT(HOUR FROM (C.COM_FECHA_FIN - C.COM_FECHA_INICIO)) +
          EXTRACT(MINUTE FROM (C.COM_FECHA_FIN - C.COM_FECHA_INICIO)) / 60) - ROUND(SUM(TOM_HORAS_SOLI), 2)
      ELSE
        0
      END, 2) AS DIFERENCIA_HORAS
FROM BIG_COMPENSATORIOS C
INNER JOIN BIG_TOMA T ON C.ID_FUNCIONARIO = T.ID_FUNCIONARIO
WHERE T.ID_FUNCIONARIO = 26 AND T.TOM_ESTADO = 2 AND C.COM_ESTADO = 2
GROUP BY C.ID_FUNCIONARIO, T.TOM_HORAS_SOLI, C.COM_ESTADO, T.TOM_ESTADO, T.TOM_MOTIVO;
    
    //1	2,5	1,5
    //1	2,5	1,5
    
SELECT
  C.ID_FUNCIONARIO,
  T.TOM_HORAS_SOLI,
  C.COM_ESTADO,
  T.TOM_ESTADO,
  T.TOM_MOTIVO,
  SUM(T.TOM_HORAS_SOLI) AS TOM_HORAS_SOLI_SUBQUERY,
  SUM(EXTRACT(HOUR FROM (C.COM_FECHA_FIN - C.COM_FECHA_INICIO)) +
    EXTRACT(MINUTE FROM (C.COM_FECHA_FIN - C.COM_FECHA_INICIO)) / 60) AS COMP_HORAS_SUBQUERY
FROM BIG_COMPENSATORIOS C
INNER JOIN BIG_TOMA T ON C.ID_FUNCIONARIO = T.ID_FUNCIONARIO
WHERE T.ID_FUNCIONARIO = 26 AND T.TOM_ESTADO = 2 AND C.COM_ESTADO = 2
GROUP BY C.ID_FUNCIONARIO, T.TOM_HORAS_SOLI, C.COM_ESTADO, T.TOM_ESTADO, T.TOM_MOTIVO;

SELECT
  C.ID_FUNCIONARIO,
  T.TOM_HORAS_SOLI,
  C.COM_ESTADO,
  T.TOM_ESTADO,
  T.TOM_MOTIVO,
  SUM(T.TOM_HORAS_SOLI) OVER (PARTITION BY C.ID_FUNCIONARIO ORDER BY T.TOM_FECHA_SOLI) AS TOM_HORAS_SOLI_SUBQUERY,
  SUM(EXTRACT(HOUR FROM (C.COM_FECHA_FIN - C.COM_FECHA_INICIO)) +
    EXTRACT(MINUTE FROM (C.COM_FECHA_FIN - C.COM_FECHA_INICIO)) / 60) OVER (PARTITION BY C.ID_FUNCIONARIO ORDER BY T.TOM_FECHA_SOLI) AS COMP_HORAS_SUBQUERY
FROM BIG_COMPENSATORIOS C
INNER JOIN BIG_TOMA T ON C.ID_FUNCIONARIO = T.ID_FUNCIONARIO
WHERE T.ID_FUNCIONARIO = 26 AND T.TOM_ESTADO = 2 AND C.COM_ESTADO = 2;


    
SELECT
  ID_FUNCIONARIO,
  TOM_HORAS_SOLI,
  COMPENSATORIOS,
  SUM(TOM_HORAS_SOLI - COMPENSATORIOS) AS DIFERENCIA,
  DIFERENCIA_HORAS AS DIFERENCIA_HORAS_REDONDEADA
FROM (
  SELECT
    --COUNT(*) AS NUM_REGISTROS,
    C.ID_FUNCIONARIO,
    ROUND(SUM(T.TOM_HORAS_SOLI), 2) AS TOM_HORAS_SOLI,
    ROUND(SUM(
				CASE WHEN C.COM_ESTADO IN (2) THEN
					EXTRACT(HOUR FROM (C.COM_FECHA_FIN - C.COM_FECHA_INICIO)) +
					EXTRACT(MINUTE FROM (C.COM_FECHA_FIN - C.COM_FECHA_INICIO)) / 60
				ELSE
					0
				END), 2)/COUNT(*) AS COMPENSATORIOS,
    ROUND(SUM(EXTRACT(HOUR FROM (C.COM_FECHA_FIN - C.COM_FECHA_INICIO)) +
      EXTRACT(MINUTE FROM (C.COM_FECHA_FIN - C.COM_FECHA_INICIO)) / 60) - TOM_HORAS_SOLI,2) AS DIFERENCIA_HORAS
  FROM BIG_TOMA T
  INNER JOIN BIG_COMPENSATORIOS C ON C.ID_FUNCIONARIO = T.ID_FUNCIONARIO
  WHERE T.ID_FUNCIONARIO = 26 AND T.TOM_ESTADO = 2 AND C.COM_ESTADO = 2
  GROUP BY C.ID_FUNCIONARIO
);

SELECT 
  /*F.FUN_NOMBRES AS FUN_NOMBRES,
  F.FUN_APELLIDOS AS FUN_APELLIDOS,
  F.FUN_CORREO AS FUN_CORREO,
  T.TOM_ESTADO AS TOM_ESTADO,
  C.COM_ESTADO AS COM_ESTADO,
  TO_CHAR(T.TOM_FECHA_SOLI, 'DD/MM/YYYY') AS TOM_FECHA_SOLI,
  T.TOM_MOTIVO,
  T.TOM_HORAS_SOLI AS TOM_HORAS_SOLI,*/
  F.FUN_NOMBRES || ' ' ||F.FUN_APELLIDOS NOMBREFUNCIONARIO,
  ROUND(SUM(TOM_HORAS_SOLI)) AS HORAS_SOLI,

  --ROUND(SUM(TOM_HORAS_SOLI), 2) AS TOTAL_TOM_HORAS_SOLI,
    ROUND(SUM(
  CASE WHEN (BITAND(COM_ESTADO, T.TOM_ESTADO)) = 2 THEN
    EXTRACT(HOUR FROM (C.COM_FECHA_FIN - C.COM_FECHA_INICIO)) +
      EXTRACT(MINUTE FROM (C.COM_FECHA_FIN - C.COM_FECHA_INICIO)) / 60 
  ELSE
    0
  END), 2) - ROUND(
    CASE WHEN (BITAND(COM_ESTADO, T.TOM_ESTADO)) = 2 THEN
        SUM(TOM_HORAS_SOLI)
    ELSE
    0
  END, 2) AS DIFERENCIA_HORAS

FROM BIG_COMPENSATORIOS C
INNER JOIN BIG_FUNCIONARIOS F ON C.ID_FUNCIONARIO = F.ID_FUNCIONARIO
INNER JOIN BIG_TOMA T ON C.ID_FUNCIONARIO = T.ID_FUNCIONARIO
WHERE C.ID_FUNCIONARIO = 26 AND C.COM_ESTADO = 2 AND T.TOM_ESTADO = 2 
GROUP BY C.ID_FUNCIONARIO, F.FUN_NOMBRES, F.FUN_APELLIDOS,
     T.TOM_HORAS_SOLI, T.TOM_ESTADO, C.COM_ESTADO;
--, F.FUN_CORREO, T.TOM_FECHA_SOLI, T.TOM_MOTIVO


/*FROM BIG_COMPENSATORIOS I
INNER JOIN BIG_FUNCIONARIOS F ON I.ID_FUNCIONARIO = F.ID_FUNCIONARIO
INNER JOIN BIG_TOMA T ON I.ID_FUNCIONARIO = T.ID_FUNCIONARIO
WHERE T.ID_TOMA = $this->intIdToma
GROUP BY I.ID_FUNCIONARIO, F.FUN_NOMBRES, F.FUN_APELLIDOS,
F.FUN_CORREO, T.TOM_MOTIVO, T.TOM_FECHA_SOLI, T.TOM_HORAS_SOLI, T.TOM_ESTADO;*/

